### PR TITLE
[IMP] - S#13042 - Hide Action Buttons on Attendances of FTOP Shift

### PR DESCRIPTION
**Pull request by phuctranfxvn**
**Support Ticket:** [S#13042 - Hide Action Buttons on Attendances of FTOP Shift](https://tms.trobz.com/web#id=13042&view_type=form&model=tms.support.ticket)

**Module to upgrade:** `coop_shift`

### CODE REVIEW

**Comment by yuntux** [comment]
Hi, here is my review :
1) I can't merge, there is a conflict due to a concurrnt merge
2) We may have only specify to change the view. However, in addition it would be better to make the verification in the controller (I mean the functions called by the buttons) and/or the model (write). If we don't, we can make the same action by XML-RPC without any controle.

**Comment by yuntux** [comment]
I talked with SImon : it's only  ergonomic purpose this time : even if we click on it the vlue is not took into account by the cron that compute the points.

In the future PR, plese tke in account XMLRPC security purpose on hiding thinkgs in views (or ask us details if it's very big or very unefficient to do it).

**Comment by phuctranfxvn** [comment]
Hello @yuntux 
I understand that we need to ensure that the xmlrpc (or any other request) should not by pass this constraint. This can be done easily. So I will make an adjustment for this PR as following
- Resolve the conflicts
- Add the constraint on the functions triggered by these buttons to prevent the action done for attendance of FTOP Shift.

For the second item, do you recommend to do it ?
Waiting for your confirmation so I can start working on this.

**Comment by yuntux** [comment]
@phuctrantrobz Juste resolve the conflict for this PR.
But keep this XMLRPC security compliance in mind for furthers tickets. Thx

**Comment by phuctranfxvn** [comment]
Thanks @yuntux 
The conflict on this PR has been resolved.
Also, I will keep in mind the security for XMLRPC (or any other internal function call).

**Pull request merged**
