### PR TITLE
[FIX] - S#14596 - [Sage export] A character makes the export failing

### PR DESCRIPTION
**Pull request by phuctranfxvn**
**Support Ticket:** [S#14596 - [Sage export] A character makes the export failing](https://tms.trobz.com/web?db=tms80#id=14596&view_type=form&model=tms.support.ticket&menu_id=275&action=284)

### CODE REVIEW

**Comment by simonjejcic** [comment]
Hello,

I am not sure this is the module we are using!

**Comment by phuctranfxvn** [comment]
Hi Simon,

Currently, we use account_export for La Louve. We don't use this module for exporting the data. I am not sure for other coops. But for this module, I can find that it is a bug

**Comment by simonjejcic** [comment]
Smile export is deprecated

It should be removed from the repository

**Comment by phuctranfxvn** [comment]
Thanks for your information, we can close this PR, I will reply to Francois for this. Thanks

**Pull request closed without merging**
